version: '3.0'
services:
  crawler_twse:
    image: monk:1.0.0
    hostname: "twse"
    command: bash -c "cd db_mission_allocate && pipenv run celery -A db_mission_allocate.tasks.worker worker --loglevel=info --concurrency=1  --hostname=%h"
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
     - my_network
    # swarm 設定
    deploy:
      mode: replicated
      replicas: 1
      # placement:
      #   constraints: [node.labels.crawler_twse == true]
    

networks:
  my_network:
    external: true
